[package]
name = "intmap-integration-test-serde"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dev-dependencies]
intmap = { path = "../..", features = ["serde"] }
proptest = "1.0.0"
serde = "1.0.0"
serde_json = "1.0.1"
